version: '3.8'

services:
  backend:
    build:
      context: ./portfolio-optimizer/portfolioOptimize
      dockerfile: Dockerfile.django  # Ensure this file exists in the backend directory
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=portfolio
      - DATABASE_USER=elliotttay
      - DATABASE_PASSWORD=
    depends_on:
      - db
    networks:
      - app_network

  frontend:
    build:
      context: ./portfolio-optimizer/portfolioOptimize
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: elliotttay
      POSTGRES_PASSWORD: ""
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
