version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9-node
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: portfolio
          POSTGRES_USER: elliotttay
          POSTGRES_PASSWORD: your_secure_password  # Set a secure password
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Wait for PostgreSQL
          command: |
            echo "Waiting for PostgreSQL to start..."
            for i in {30..0}; do
              if pg_isready -h localhost -p 5432; then
                echo "PostgreSQL is up!"
                break
              fi
              echo "PostgreSQL is unavailable - waiting..."
              sleep 1
            done

  test:
    docker:
      - image: circleci/python:3.9-node
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: portfolio
          POSTGRES_USER: elliotttay
          POSTGRES_PASSWORD: your_secure_password  # Set the same secure password
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Run Django Tests
          command: python manage.py test
      - run:
          name: Run Frontend Tests
          command: |
            cd portfolioOptimizer
            npm test -- --watchAll=false

  deploy:
    docker:
      - image: circleci/python:3.9-node
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: |
            # Your deployment commands here

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
