version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: portfolio
          POSTGRES_USER: elliotttay
          POSTGRES_PASSWORD: your_password_here  # Set a strong password here
    steps:
      - checkout  # Check out your code
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt  # Install dependencies
      - run:
          name: Start PostgreSQL
          command: |
            sudo service postgresql start
      - run:
          name: Migrate Database
          command: python manage.py migrate
      - run:
          name: Run Tests
          command: python manage.py test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

