version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9  # Python 3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python manage.py test  # Run Django tests

workflows:
  version: 2
  build:
    jobs:
      - build