version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: $DATABASE_USER
          POSTGRES_DB: $DATABASE_NAME
          POSTGRES_PASSWORD: $DATABASE_PASSWORD
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            python manage.py test
workflows:
  version: 2
  build:
    jobs:
      - build