version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9-node
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: portfolio
          POSTGRES_USER: elliotttay
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Wait for PostgreSQL
          command: |
            echo "Waiting for PostgreSQL to start..."
            for i in {30..0}; do
              if pg_isready -h localhost -p 5432; then
                echo "PostgreSQL is up!"
                break
              fi
              echo "PostgreSQL is unavailable - waiting..."
              sleep 1
            done
      - run:
          name: Migrate Database
          command: python manage.py migrate
      - run:
          name: Run Django Tests
          command: python manage.py test
      - run:
          name: Check Node.js and npm Versions
          command: |
            echo "Checking Node.js version..."
            node -v
            echo "Checking npm version..."
            npm -v
      - run:
          name: Install Node.js Dependencies
          command: |
            cd portfolioOptimizer
            npm install 
      - run:
          name: Run Frontend Tests
          command: |
            cd portfolioOptimizer
            npm test -- --watchAll=false

  lint:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Run ESLint
          command: |
            cd portfolioOptimizer
            npm run lint -- --verbose  # Add --verbose for more detailed output

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application..."

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - deploy:
          requires:
            - build
